FROM lab-safety-monitor-monitor-worker:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y rabbitmq-server && rm -rf /var/lib/apt/lists/*

RUN rabbitmq-plugins enable --offline rabbitmq_management

RUN mkdir -p /etc/rabbitmq

COPY docker/rabbitmq/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

EXPOSE 5672 15672

CMD ["rabbitmq-server"]
